image: golang:1.26.1

stages:
  - lint
  - sast
  - test
  - build

before_script:
  - go mod download
  - go mod verify

lint:
  stage: lint
  script:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - golangci-lint run ./...
  allow_failure: false

sast:
  stage: sast
  script:
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
    - gosec ./...
  allow_failure: false

test:
  stage: test
  script:
    - go test -v -race -coverprofile=coverage.out ./...
  artifacts:
    paths:
      - coverage.out
    expire_in: 1 week
  coverage: '/coverage: \d+.\d+% of statements/'

build:
  stage: build
  script:
    - go build -o calc ./cmd/app
  artifacts:
    paths:
      - calc
    expire_in: 1 week